const productData = [
  {
    id: '1',
    image: '/basindouble.png',
    title: 'White Bathroom Basin',
    description: 'White Bathroom Basin',
    price: '2200',
    category: 'Bathroomware',
    size: '100 x 100',
    sku: 'BNHSY78',
    newArrival: false,
    sale: false,
  },
  {
    id: '2',
    image: '/tub.png',
    title: 'White Bathroom Basin',
    description: 'White Bathroom Basin',
    price: '2200',
    category: 'Bathroomware',
    size: '100 x 100',
    sku: 'BBHSTY',
    newArrival: false,
    sale: false,
  },
  {
    id: '3',
    image: '/bath-storage.png',
    title: 'White Bathroom Basin',
    description: 'White Bathroom Basin',
    price: '2200',
    category: 'Bathroomware',
    size: '100 x 100',
    sku: 'AABGSYU',
    newArrival: false,
    sale: false,
  },
  {
    id: '4',
    image: '/basindouble.png',
    title: 'White Bathroom Basin',
    description: 'White Bathroom Basin',
    price: '2200',
    category: 'Bathroomware',
    size: '100 x 100',
    sku: 'OOISYUTYS',
    newArrival: false,
    sale: false,
  },
  {
    id: '5',
    image: '/tub.png',
    title: 'White Bathroom Basin',
    description: 'White Bathroom Basin',
    price: '2200',
    category: 'Bathroomware',
    size: '100 x 100',
    sku: 'NNSHUYS',
    newArrival: false,
    sale: false,
  },
  {
    id: '6',
    image: '/bath-storage.png',
    title: 'White Bathroom Basin',
    description: 'White Bathroom Basin',
    price: '2200',
    category: 'Bathroomware',
    size: '100 x 100',
    sku: 'NNHJSU',
    newArrival: false,
    sale: false,
  },
  {
    id: '7',
    image: '/tub.png',
    title: 'White Bathroom Basin',
    description: 'White Bathroom Basin',
    price: '2200',
    category: 'Bathroomware',
    size: '100 x 100',
    sku: 'IUSYUS',
    newArrival: false,
    sale: false,
  },
  {
    id: '8',
    image: '/basindouble.png',
    title: 'White Bathroom Basin',
    description: 'White Bathroom Basin',
    price: '2200',
    category: 'Bathroomware',
    size: '100 x 100',
    sku: 'KKSLISUS',
    newArrival: false,
    sale: false,
  },
];

export default productData;
